import Head from 'next/head'
import Image from 'next/image'
import { Button } from '../components/Button'
import { Inter } from '@next/font/google'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-[#1d1d1b]'>
        <div className='max-w-xl mx-auto'>
          <div className='flex flex-col gap-5 items-center justify-center h-screen'>
            <Image 
              src="/img/logo-beach-grill.webp"
              alt="Beach Grill by SABBIA"
              width={200}
              height={100}
            />
            <Button buttonUrl="#" buttonText="Alimentos"/>
            <Button buttonUrl="#" buttonText="Bebidas"/>
            <Button buttonUrl="#" buttonText="Wifi"/>
            <Button buttonUrl="#" buttonText="Facturacion"/>
            <Button buttonUrl="#" buttonText="Feedback"/>
            <Button buttonUrl="#" buttonText="Reservar"/>
          </div>
        </div>

      </main>
    </>
  )
}
